### ISSUE TITLE
OSM attribution and usage policy

### ISSUE THREAD

**Issue by Matthias84** [fraunhoferfokus/particity#2]
Hi, thanks for using OSM, but could you please add the attribution as required by the legal terms? Also it might be nessesary to respect the tile usage policy, if you use the official tile server.

**Comment by stampedev** [comment]
Thanks, we definitely missed that! We are using Leaflet and had attribution switched off for some weird reason. Changes are committed, deployed to the demo-server and there's a note in the  [installation docs](https://fraunhoferfokus.github.io/particity/install.html)
regarding that issue.

Besides attribution, regarding our demo site and the usage policy of OSM - I think we are ok for now, as there is only a handful of exemplary entries (and we don't have that much traffic anyway ;)). Although users are free to test and publish more entries, we are having an eye on that server and additionally the database gets reset each night.

**Comment by Matthias84** [comment]
I wasn't aware if this is a selfhosting solution, so I tried to give a hint and avoid troubles for the other admins who might serve it for big cities etc. and get banned by osm.org

Thanks for fixing @stampedev
