### ISSUE TITLE
Switch to common licenses

### ISSUE THREAD

**Issue by Matthias84** [fraunhoferfokus/particity#3]
The current [LICENSE](LICENSE) make it hard to predict if it's ok or not to contribute/modify/fork this project and if it's getting illegal to mix with LGPL/BSD/... stuff. Please consider a switch to a common free/open source license.

**Comment by stampedev** [comment]
Actually the [license](https://fraunhoferfokus.github.io/particity/license.html) is a typical 3-clause BSD and as such should mix quite well with any other license in the field. Apart from that, I'm no lawyer and we just wanted to avoid any copyleft related terms that could restrict the adoption of the project by commercial businesses (yet serving the public good).
