### ISSUE TITLE
Offer docker

### ISSUE THREAD

**Issue by Matthias84** [fraunhoferfokus/particity#4]
It would be nice to offer an easy way for selfhosting e.g. Docker/Vagrant/Heroku/...

**Comment by stampedev** [comment]
Unfortunately we currently have no expertise in this field. However, as mentioned in the [TODOs](https://fraunhoferfokus.github.io/particity/todo.html) (subject to change) and in (#1)[https://github.com/fraunhoferfokus/particity/issues/1] we are aware that more comfortable ways of deployment & installation are required for upcoming releases. Feel free to get involved with particity and provide documentation or changes on the topic!

**Comment by stampedev** [comment]
Docker support was just added in HEAD. Still only makes sense with a (more or less) automated/guided install, which I am currently working on. Seeing forward to get a user-friendly solution for the upcoming release 0.9.4.
