### ISSUE TITLE
leading 0 in Zip codes disappears

### ISSUE THREAD

**Issue by renarena** [fraunhoferfokus/particity#9]
I dont know if its a Liferay problem or one of Particity, but after creating an Angebot, the leading 0 of a zip code like 01234 disappears (a common problem in calc sheets when PLZ is a number rather then a text)

**Comment by stampedev** [comment]
Thanks for reporting! Indeed we assumed the ZIP to be a numeric value which is of course not correct. Working to fix this asap.
